#æœåŠ¡é…ç½®
server:
  #ç«¯å£
  port: 9995
  #æœåŠ¡ç¼–ç 
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: zzyl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 6MB
  #æ•°æ®æºé…ç½®
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/zhyl?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
  activiti:
    #æ˜¯å¦è®©activitiè‡ªåŠ¨åˆ›å»ºæ‰€æœ‰çš„å†å²è¡¨
    history-level: full
    #æ˜¯å¦éœ€è¦ä½¿ç”¨å†å²è¡¨,é»˜è®¤falseä¸ä½¿ç”¨,è€Œé…ç½®trueæ˜¯ä½¿ç”¨å†å²è¡¨
    db-history-used: true
    #æµç¨‹è‡ªåŠ¨éƒ¨ç½²ï¼Œå…³é—­ï¼Œéœ€è¦æ‰‹åŠ¨éƒ¨ç½²æµç¨‹ æœåŠ¡å¯åŠ¨çš„æ—¶å€™è‡ªåŠ¨æ£€æŸ¥resourcesç›®å½•ä¸‹çš„bpmnæ–‡ä»¶ å¦‚æœä¸ºtrueè‡ªåŠ¨éƒ¨ç½²æµç¨‹
    check-process-definitions: false
    #å…³é—­å¯åŠ¨æœåŠ¡è‡ªåŠ¨æ¡†æ¶éƒ¨ç½²
    deployment-mode: never-fail
# MyBatisé…ç½®
mybatis:
  #mapperé…ç½®æ–‡ä»¶
  mapper-locations: classpath*:mapper*/*Mapper.xml
  type-aliases-package: com.zzyl.entity
  configuration:
    # è¿™ä¸ªé…ç½®ä¼šå°†æ‰§è¡Œçš„sqlæ‰“å°å‡ºæ¥ï¼Œåœ¨å¼€å‘æˆ–æµ‹è¯•çš„æ—¶å€™å¯ä»¥ç”¨
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # é©¼å³°ä¸‹åˆ’çº¿è½¬æ¢
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
logging:
  config: classpath:logback.xml
  level:
    org.springframework.web.socket: debug
knife4j:
  enable: true
zzyl:
  framework:
    security:
      ignore-url:
#        - /**
        - /resource/menus/**
        - /resource/myButten/**
        - /customer/**
        - /security/login
        - /security/logout
        - /doc.html
        - /*-swagger/**
        - /swagger-resources
        - /v2/api-docs
        - /webjars/**
        - /common/**
        - /ws/**
      defaule-password: 888itcast.CN764%...
    swagger:
      swagger-path: com.zzyl.controller
      title: æ™ºæ…§å…»è€æœåŠ¡
      description: æ™ºæ…§å…»è€
      contact-name: ğŸ–ğŸ–
      contact-url: www.itheima.com
      contact-email: itheima@itcast.cn
    jwt:
      base64-encoded-secret-key: $2a$10$PVtHnkj86mJgf6li/yron.LRx/cQAlaiZkBJ9BeogCNTryXJRT1YC
      ttl: 3600000
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      accessKeyId: your-access-key-id
      accessKeySecret: your-access-key-id
      bucketName: zwyhmleadnews
  wechat:
    appId: wxa54e0997e8b6649e
    appSecret: 9e4b693aa8cee71a9077e15dcac30b52
#  wechat:
#    appId: wxa37ad44a9d9ab836
#    appSecret: 85ef0e856bafed3eb55e279c3a48fa49
  aliyun:
    accessKeyId: {your-access-key-id}
    accessKeySecret: {your-access-key-secret}
    consumerGroupId: DEFAULT_GROUP
#    consumerGroupId: 0CP9WrqP8Q1lLaWFjli9000100
    regionId: cn-hangzhou
    iotInstanceId: iot-06z00frq8umvkx2
    host: iot-06z00frq8umvkx2.amqp.iothub.aliyuncs.com

management:
  health:
    rabbit:
      enabled: false
xxl:
  job:
    admin:
      addresses: http://192.168.200.146:8888/xxl-job-admin
    executor:
      appname: zzyl-dev-executor
      port: 9999